######################## default configuration ####################
baseURL = "https://www.codeflamingo.eu/"
languageCode = "en-us"
title = "Code Flamingo"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = "codeflamingo"

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"
[[params.plugins.css]]
URL = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "About"
URL = "about/"
weight = 1

[[menu.main]]
name = "Post"
URL = "blog/"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 3

# footer menu
[[menu.footer]]
name = "About"
URL = "about/"
weight = 1

[[menu.footer]]
name = "Post"
URL = "blog/"
weight = 2

[[menu.footer]]
name = "Contact"
URL = "contact/"
weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Suryakiran Maruvada"
# Google Analitycs
googleAnalitycsID = "G-MZ2RZE93ZM"
# Contact Information
# mobile = "0124857985320"
email = "suryakiranmaruvada09@gmail.com"
location = "Munich, Germany"
# copyright
copyright = "| copyright &copy; 2023 Suryakiran Maruvada All Rights Reserved |"
custom_css = ["css/custom.css"]

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ news letter ########################
# [params.newsletter]
# enable = true
# title = "Join Our Newsletter"
# content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
# [[params.social]]
# title = "facebook"
# icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
# link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/SurKM9"

# [[params.social]]
# title = "instagram"
# icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
# link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/SurKM9"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/suryakiran-maruvada-97622941/"

[markup]
  [markup.highlight]
    style = "dracula"
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false   # <--- THIS IS THE MAGIC BULLET
    noClasses = true